//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: proto/api/api.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

public protocol Iotexapi_APIServiceGetAccountCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetAccountCallBase: ClientCallUnaryBase<Iotexapi_GetAccountRequest, Iotexapi_GetAccountResponse>, Iotexapi_APIServiceGetAccountCall {
  override class var method: String { return "/iotexapi.APIService/GetAccount" }
}

public protocol Iotexapi_APIServiceGetActionsCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetActionsCallBase: ClientCallUnaryBase<Iotexapi_GetActionsRequest, Iotexapi_GetActionsResponse>, Iotexapi_APIServiceGetActionsCall {
  override class var method: String { return "/iotexapi.APIService/GetActions" }
}

public protocol Iotexapi_APIServiceGetBlockMetasCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetBlockMetasCallBase: ClientCallUnaryBase<Iotexapi_GetBlockMetasRequest, Iotexapi_GetBlockMetasResponse>, Iotexapi_APIServiceGetBlockMetasCall {
  override class var method: String { return "/iotexapi.APIService/GetBlockMetas" }
}

public protocol Iotexapi_APIServiceGetChainMetaCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetChainMetaCallBase: ClientCallUnaryBase<Iotexapi_GetChainMetaRequest, Iotexapi_GetChainMetaResponse>, Iotexapi_APIServiceGetChainMetaCall {
  override class var method: String { return "/iotexapi.APIService/GetChainMeta" }
}

public protocol Iotexapi_APIServiceGetServerMetaCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetServerMetaCallBase: ClientCallUnaryBase<Iotexapi_GetServerMetaRequest, Iotexapi_GetServerMetaResponse>, Iotexapi_APIServiceGetServerMetaCall {
  override class var method: String { return "/iotexapi.APIService/GetServerMeta" }
}

public protocol Iotexapi_APIServiceSendActionCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceSendActionCallBase: ClientCallUnaryBase<Iotexapi_SendActionRequest, Iotexapi_SendActionResponse>, Iotexapi_APIServiceSendActionCall {
  override class var method: String { return "/iotexapi.APIService/SendAction" }
}

public protocol Iotexapi_APIServiceGetReceiptByActionCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetReceiptByActionCallBase: ClientCallUnaryBase<Iotexapi_GetReceiptByActionRequest, Iotexapi_GetReceiptByActionResponse>, Iotexapi_APIServiceGetReceiptByActionCall {
  override class var method: String { return "/iotexapi.APIService/GetReceiptByAction" }
}

public protocol Iotexapi_APIServiceReadContractCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceReadContractCallBase: ClientCallUnaryBase<Iotexapi_ReadContractRequest, Iotexapi_ReadContractResponse>, Iotexapi_APIServiceReadContractCall {
  override class var method: String { return "/iotexapi.APIService/ReadContract" }
}

public protocol Iotexapi_APIServiceSuggestGasPriceCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceSuggestGasPriceCallBase: ClientCallUnaryBase<Iotexapi_SuggestGasPriceRequest, Iotexapi_SuggestGasPriceResponse>, Iotexapi_APIServiceSuggestGasPriceCall {
  override class var method: String { return "/iotexapi.APIService/SuggestGasPrice" }
}

public protocol Iotexapi_APIServiceEstimateGasForActionCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceEstimateGasForActionCallBase: ClientCallUnaryBase<Iotexapi_EstimateGasForActionRequest, Iotexapi_EstimateGasForActionResponse>, Iotexapi_APIServiceEstimateGasForActionCall {
  override class var method: String { return "/iotexapi.APIService/EstimateGasForAction" }
}

public protocol Iotexapi_APIServiceEstimateActionGasConsumptionCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceEstimateActionGasConsumptionCallBase: ClientCallUnaryBase<Iotexapi_EstimateActionGasConsumptionRequest, Iotexapi_EstimateActionGasConsumptionResponse>, Iotexapi_APIServiceEstimateActionGasConsumptionCall {
  override class var method: String { return "/iotexapi.APIService/EstimateActionGasConsumption" }
}

public protocol Iotexapi_APIServiceReadStateCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceReadStateCallBase: ClientCallUnaryBase<Iotexapi_ReadStateRequest, Iotexapi_ReadStateResponse>, Iotexapi_APIServiceReadStateCall {
  override class var method: String { return "/iotexapi.APIService/ReadState" }
}

public protocol Iotexapi_APIServiceGetEpochMetaCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetEpochMetaCallBase: ClientCallUnaryBase<Iotexapi_GetEpochMetaRequest, Iotexapi_GetEpochMetaResponse>, Iotexapi_APIServiceGetEpochMetaCall {
  override class var method: String { return "/iotexapi.APIService/GetEpochMeta" }
}

public protocol Iotexapi_APIServiceGetRawBlocksCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetRawBlocksCallBase: ClientCallUnaryBase<Iotexapi_GetRawBlocksRequest, Iotexapi_GetRawBlocksResponse>, Iotexapi_APIServiceGetRawBlocksCall {
  override class var method: String { return "/iotexapi.APIService/GetRawBlocks" }
}

public protocol Iotexapi_APIServiceGetLogsCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetLogsCallBase: ClientCallUnaryBase<Iotexapi_GetLogsRequest, Iotexapi_GetLogsResponse>, Iotexapi_APIServiceGetLogsCall {
  override class var method: String { return "/iotexapi.APIService/GetLogs" }
}

public protocol Iotexapi_APIServiceGetTransactionLogByActionHashCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetTransactionLogByActionHashCallBase: ClientCallUnaryBase<Iotexapi_GetTransactionLogByActionHashRequest, Iotexapi_GetTransactionLogByActionHashResponse>, Iotexapi_APIServiceGetTransactionLogByActionHashCall {
  override class var method: String { return "/iotexapi.APIService/GetTransactionLogByActionHash" }
}

public protocol Iotexapi_APIServiceGetTransactionLogByBlockHeightCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetTransactionLogByBlockHeightCallBase: ClientCallUnaryBase<Iotexapi_GetTransactionLogByBlockHeightRequest, Iotexapi_GetTransactionLogByBlockHeightResponse>, Iotexapi_APIServiceGetTransactionLogByBlockHeightCall {
  override class var method: String { return "/iotexapi.APIService/GetTransactionLogByBlockHeight" }
}

public protocol Iotexapi_APIServiceStreamBlocksCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Iotexapi_StreamBlocksResponse?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Iotexapi_StreamBlocksResponse?>) -> Void) throws
}

public extension Iotexapi_APIServiceStreamBlocksCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Iotexapi_StreamBlocksResponse? { return try self._receive(timeout: timeout) }
}

fileprivate final class Iotexapi_APIServiceStreamBlocksCallBase: ClientCallServerStreamingBase<Iotexapi_StreamBlocksRequest, Iotexapi_StreamBlocksResponse>, Iotexapi_APIServiceStreamBlocksCall {
  override class var method: String { return "/iotexapi.APIService/StreamBlocks" }
}

public protocol Iotexapi_APIServiceStreamLogsCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Iotexapi_StreamLogsResponse?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Iotexapi_StreamLogsResponse?>) -> Void) throws
}

public extension Iotexapi_APIServiceStreamLogsCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Iotexapi_StreamLogsResponse? { return try self._receive(timeout: timeout) }
}

fileprivate final class Iotexapi_APIServiceStreamLogsCallBase: ClientCallServerStreamingBase<Iotexapi_StreamLogsRequest, Iotexapi_StreamLogsResponse>, Iotexapi_APIServiceStreamLogsCall {
  override class var method: String { return "/iotexapi.APIService/StreamLogs" }
}

public protocol Iotexapi_APIServiceGetActPoolActionsCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetActPoolActionsCallBase: ClientCallUnaryBase<Iotexapi_GetActPoolActionsRequest, Iotexapi_GetActPoolActionsResponse>, Iotexapi_APIServiceGetActPoolActionsCall {
  override class var method: String { return "/iotexapi.APIService/GetActPoolActions" }
}

public protocol Iotexapi_APIServiceGetEvmTransfersByActionHashCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetEvmTransfersByActionHashCallBase: ClientCallUnaryBase<Iotexapi_GetEvmTransfersByActionHashRequest, Iotexapi_GetEvmTransfersByActionHashResponse>, Iotexapi_APIServiceGetEvmTransfersByActionHashCall {
  override class var method: String { return "/iotexapi.APIService/GetEvmTransfersByActionHash" }
}

public protocol Iotexapi_APIServiceGetEvmTransfersByBlockHeightCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetEvmTransfersByBlockHeightCallBase: ClientCallUnaryBase<Iotexapi_GetEvmTransfersByBlockHeightRequest, Iotexapi_GetEvmTransfersByBlockHeightResponse>, Iotexapi_APIServiceGetEvmTransfersByBlockHeightCall {
  override class var method: String { return "/iotexapi.APIService/GetEvmTransfersByBlockHeight" }
}

public protocol Iotexapi_APIServiceGetElectionBucketsCall: ClientCallUnary {}

fileprivate final class Iotexapi_APIServiceGetElectionBucketsCallBase: ClientCallUnaryBase<Iotexapi_GetElectionBucketsRequest, Iotexapi_GetElectionBucketsResponse>, Iotexapi_APIServiceGetElectionBucketsCall {
  override class var method: String { return "/iotexapi.APIService/GetElectionBuckets" }
}


/// Instantiate Iotexapi_APIServiceServiceClient, then call methods of this protocol to make API calls.
public protocol Iotexapi_APIServiceService: ServiceClient {
  /// Synchronous. Unary.
  func getAccount(_ request: Iotexapi_GetAccountRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetAccountResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getAccount(_ request: Iotexapi_GetAccountRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetAccountResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetAccountCall

  /// Synchronous. Unary.
  func getActions(_ request: Iotexapi_GetActionsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetActionsResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getActions(_ request: Iotexapi_GetActionsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActionsCall

  /// Synchronous. Unary.
  func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetBlockMetasResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetBlockMetasResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetBlockMetasCall

  /// Synchronous. Unary.
  func getChainMeta(_ request: Iotexapi_GetChainMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetChainMetaResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getChainMeta(_ request: Iotexapi_GetChainMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetChainMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetChainMetaCall

  /// Synchronous. Unary.
  func getServerMeta(_ request: Iotexapi_GetServerMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetServerMetaResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getServerMeta(_ request: Iotexapi_GetServerMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetServerMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetServerMetaCall

  /// Synchronous. Unary.
  func sendAction(_ request: Iotexapi_SendActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_SendActionResponse
  /// Asynchronous. Unary.
  @discardableResult
  func sendAction(_ request: Iotexapi_SendActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_SendActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSendActionCall

  /// Synchronous. Unary.
  func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetReceiptByActionResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetReceiptByActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetReceiptByActionCall

  /// Synchronous. Unary.
  func readContract(_ request: Iotexapi_ReadContractRequest, metadata customMetadata: Metadata) throws -> Iotexapi_ReadContractResponse
  /// Asynchronous. Unary.
  @discardableResult
  func readContract(_ request: Iotexapi_ReadContractRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_ReadContractResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadContractCall

  /// Synchronous. Unary.
  func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest, metadata customMetadata: Metadata) throws -> Iotexapi_SuggestGasPriceResponse
  /// Asynchronous. Unary.
  @discardableResult
  func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_SuggestGasPriceResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSuggestGasPriceCall

  /// Synchronous. Unary.
  func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_EstimateGasForActionResponse
  /// Asynchronous. Unary.
  @discardableResult
  func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_EstimateGasForActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateGasForActionCall

  /// Synchronous. Unary.
  func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_EstimateActionGasConsumptionResponse
  /// Asynchronous. Unary.
  @discardableResult
  func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_EstimateActionGasConsumptionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateActionGasConsumptionCall

  /// Synchronous. Unary.
  func readState(_ request: Iotexapi_ReadStateRequest, metadata customMetadata: Metadata) throws -> Iotexapi_ReadStateResponse
  /// Asynchronous. Unary.
  @discardableResult
  func readState(_ request: Iotexapi_ReadStateRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_ReadStateResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadStateCall

  /// Synchronous. Unary.
  func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEpochMetaResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEpochMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEpochMetaCall

  /// Synchronous. Unary.
  func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetRawBlocksResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetRawBlocksResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetRawBlocksCall

  /// Synchronous. Unary.
  func getLogs(_ request: Iotexapi_GetLogsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetLogsResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getLogs(_ request: Iotexapi_GetLogsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetLogsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetLogsCall

  /// Synchronous. Unary.
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByActionHashResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByActionHashCall

  /// Synchronous. Unary.
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByBlockHeightCall

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func streamBlocks(_ request: Iotexapi_StreamBlocksRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamBlocksCall

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func streamLogs(_ request: Iotexapi_StreamLogsRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamLogsCall

  /// Synchronous. Unary.
  func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetActPoolActionsResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetActPoolActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActPoolActionsCall

  /// Synchronous. Unary.
  func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEvmTransfersByActionHashResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEvmTransfersByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByActionHashCall

  /// Synchronous. Unary.
  func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEvmTransfersByBlockHeightResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEvmTransfersByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByBlockHeightCall

  /// Synchronous. Unary.
  func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetElectionBucketsResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetElectionBucketsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetElectionBucketsCall

}

public extension Iotexapi_APIServiceService {
  /// Synchronous. Unary.
  func getAccount(_ request: Iotexapi_GetAccountRequest) throws -> Iotexapi_GetAccountResponse {
    return try self.getAccount(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getAccount(_ request: Iotexapi_GetAccountRequest, completion: @escaping (Iotexapi_GetAccountResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetAccountCall {
    return try self.getAccount(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getActions(_ request: Iotexapi_GetActionsRequest) throws -> Iotexapi_GetActionsResponse {
    return try self.getActions(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getActions(_ request: Iotexapi_GetActionsRequest, completion: @escaping (Iotexapi_GetActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActionsCall {
    return try self.getActions(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest) throws -> Iotexapi_GetBlockMetasResponse {
    return try self.getBlockMetas(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest, completion: @escaping (Iotexapi_GetBlockMetasResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetBlockMetasCall {
    return try self.getBlockMetas(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getChainMeta(_ request: Iotexapi_GetChainMetaRequest) throws -> Iotexapi_GetChainMetaResponse {
    return try self.getChainMeta(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getChainMeta(_ request: Iotexapi_GetChainMetaRequest, completion: @escaping (Iotexapi_GetChainMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetChainMetaCall {
    return try self.getChainMeta(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getServerMeta(_ request: Iotexapi_GetServerMetaRequest) throws -> Iotexapi_GetServerMetaResponse {
    return try self.getServerMeta(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getServerMeta(_ request: Iotexapi_GetServerMetaRequest, completion: @escaping (Iotexapi_GetServerMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetServerMetaCall {
    return try self.getServerMeta(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func sendAction(_ request: Iotexapi_SendActionRequest) throws -> Iotexapi_SendActionResponse {
    return try self.sendAction(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func sendAction(_ request: Iotexapi_SendActionRequest, completion: @escaping (Iotexapi_SendActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSendActionCall {
    return try self.sendAction(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest) throws -> Iotexapi_GetReceiptByActionResponse {
    return try self.getReceiptByAction(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest, completion: @escaping (Iotexapi_GetReceiptByActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetReceiptByActionCall {
    return try self.getReceiptByAction(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func readContract(_ request: Iotexapi_ReadContractRequest) throws -> Iotexapi_ReadContractResponse {
    return try self.readContract(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func readContract(_ request: Iotexapi_ReadContractRequest, completion: @escaping (Iotexapi_ReadContractResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadContractCall {
    return try self.readContract(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest) throws -> Iotexapi_SuggestGasPriceResponse {
    return try self.suggestGasPrice(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest, completion: @escaping (Iotexapi_SuggestGasPriceResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSuggestGasPriceCall {
    return try self.suggestGasPrice(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest) throws -> Iotexapi_EstimateGasForActionResponse {
    return try self.estimateGasForAction(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest, completion: @escaping (Iotexapi_EstimateGasForActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateGasForActionCall {
    return try self.estimateGasForAction(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest) throws -> Iotexapi_EstimateActionGasConsumptionResponse {
    return try self.estimateActionGasConsumption(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest, completion: @escaping (Iotexapi_EstimateActionGasConsumptionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateActionGasConsumptionCall {
    return try self.estimateActionGasConsumption(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func readState(_ request: Iotexapi_ReadStateRequest) throws -> Iotexapi_ReadStateResponse {
    return try self.readState(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func readState(_ request: Iotexapi_ReadStateRequest, completion: @escaping (Iotexapi_ReadStateResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadStateCall {
    return try self.readState(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest) throws -> Iotexapi_GetEpochMetaResponse {
    return try self.getEpochMeta(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest, completion: @escaping (Iotexapi_GetEpochMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEpochMetaCall {
    return try self.getEpochMeta(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest) throws -> Iotexapi_GetRawBlocksResponse {
    return try self.getRawBlocks(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest, completion: @escaping (Iotexapi_GetRawBlocksResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetRawBlocksCall {
    return try self.getRawBlocks(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getLogs(_ request: Iotexapi_GetLogsRequest) throws -> Iotexapi_GetLogsResponse {
    return try self.getLogs(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getLogs(_ request: Iotexapi_GetLogsRequest, completion: @escaping (Iotexapi_GetLogsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetLogsCall {
    return try self.getLogs(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest) throws -> Iotexapi_GetTransactionLogByActionHashResponse {
    return try self.getTransactionLogByActionHash(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByActionHashCall {
    return try self.getTransactionLogByActionHash(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse {
    return try self.getTransactionLogByBlockHeight(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByBlockHeightCall {
    return try self.getTransactionLogByBlockHeight(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  func streamBlocks(_ request: Iotexapi_StreamBlocksRequest, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamBlocksCall {
    return try self.streamBlocks(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  func streamLogs(_ request: Iotexapi_StreamLogsRequest, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamLogsCall {
    return try self.streamLogs(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest) throws -> Iotexapi_GetActPoolActionsResponse {
    return try self.getActPoolActions(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest, completion: @escaping (Iotexapi_GetActPoolActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActPoolActionsCall {
    return try self.getActPoolActions(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest) throws -> Iotexapi_GetEvmTransfersByActionHashResponse {
    return try self.getEvmTransfersByActionHash(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest, completion: @escaping (Iotexapi_GetEvmTransfersByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByActionHashCall {
    return try self.getEvmTransfersByActionHash(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest) throws -> Iotexapi_GetEvmTransfersByBlockHeightResponse {
    return try self.getEvmTransfersByBlockHeight(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest, completion: @escaping (Iotexapi_GetEvmTransfersByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByBlockHeightCall {
    return try self.getEvmTransfersByBlockHeight(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest) throws -> Iotexapi_GetElectionBucketsResponse {
    return try self.getElectionBuckets(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest, completion: @escaping (Iotexapi_GetElectionBucketsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetElectionBucketsCall {
    return try self.getElectionBuckets(request, metadata: self.metadata, completion: completion)
  }

}

public final class Iotexapi_APIServiceServiceClient: ServiceClientBase, Iotexapi_APIServiceService {
  /// Synchronous. Unary.
  public func getAccount(_ request: Iotexapi_GetAccountRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetAccountResponse {
    return try Iotexapi_APIServiceGetAccountCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getAccount(_ request: Iotexapi_GetAccountRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetAccountResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetAccountCall {
    return try Iotexapi_APIServiceGetAccountCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getActions(_ request: Iotexapi_GetActionsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetActionsResponse {
    return try Iotexapi_APIServiceGetActionsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getActions(_ request: Iotexapi_GetActionsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActionsCall {
    return try Iotexapi_APIServiceGetActionsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetBlockMetasResponse {
    return try Iotexapi_APIServiceGetBlockMetasCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getBlockMetas(_ request: Iotexapi_GetBlockMetasRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetBlockMetasResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetBlockMetasCall {
    return try Iotexapi_APIServiceGetBlockMetasCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getChainMeta(_ request: Iotexapi_GetChainMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetChainMetaResponse {
    return try Iotexapi_APIServiceGetChainMetaCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getChainMeta(_ request: Iotexapi_GetChainMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetChainMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetChainMetaCall {
    return try Iotexapi_APIServiceGetChainMetaCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getServerMeta(_ request: Iotexapi_GetServerMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetServerMetaResponse {
    return try Iotexapi_APIServiceGetServerMetaCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getServerMeta(_ request: Iotexapi_GetServerMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetServerMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetServerMetaCall {
    return try Iotexapi_APIServiceGetServerMetaCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func sendAction(_ request: Iotexapi_SendActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_SendActionResponse {
    return try Iotexapi_APIServiceSendActionCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func sendAction(_ request: Iotexapi_SendActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_SendActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSendActionCall {
    return try Iotexapi_APIServiceSendActionCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetReceiptByActionResponse {
    return try Iotexapi_APIServiceGetReceiptByActionCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getReceiptByAction(_ request: Iotexapi_GetReceiptByActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetReceiptByActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetReceiptByActionCall {
    return try Iotexapi_APIServiceGetReceiptByActionCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func readContract(_ request: Iotexapi_ReadContractRequest, metadata customMetadata: Metadata) throws -> Iotexapi_ReadContractResponse {
    return try Iotexapi_APIServiceReadContractCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func readContract(_ request: Iotexapi_ReadContractRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_ReadContractResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadContractCall {
    return try Iotexapi_APIServiceReadContractCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest, metadata customMetadata: Metadata) throws -> Iotexapi_SuggestGasPriceResponse {
    return try Iotexapi_APIServiceSuggestGasPriceCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func suggestGasPrice(_ request: Iotexapi_SuggestGasPriceRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_SuggestGasPriceResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceSuggestGasPriceCall {
    return try Iotexapi_APIServiceSuggestGasPriceCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_EstimateGasForActionResponse {
    return try Iotexapi_APIServiceEstimateGasForActionCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func estimateGasForAction(_ request: Iotexapi_EstimateGasForActionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_EstimateGasForActionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateGasForActionCall {
    return try Iotexapi_APIServiceEstimateGasForActionCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest, metadata customMetadata: Metadata) throws -> Iotexapi_EstimateActionGasConsumptionResponse {
    return try Iotexapi_APIServiceEstimateActionGasConsumptionCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func estimateActionGasConsumption(_ request: Iotexapi_EstimateActionGasConsumptionRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_EstimateActionGasConsumptionResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceEstimateActionGasConsumptionCall {
    return try Iotexapi_APIServiceEstimateActionGasConsumptionCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func readState(_ request: Iotexapi_ReadStateRequest, metadata customMetadata: Metadata) throws -> Iotexapi_ReadStateResponse {
    return try Iotexapi_APIServiceReadStateCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func readState(_ request: Iotexapi_ReadStateRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_ReadStateResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceReadStateCall {
    return try Iotexapi_APIServiceReadStateCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEpochMetaResponse {
    return try Iotexapi_APIServiceGetEpochMetaCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getEpochMeta(_ request: Iotexapi_GetEpochMetaRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEpochMetaResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEpochMetaCall {
    return try Iotexapi_APIServiceGetEpochMetaCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetRawBlocksResponse {
    return try Iotexapi_APIServiceGetRawBlocksCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getRawBlocks(_ request: Iotexapi_GetRawBlocksRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetRawBlocksResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetRawBlocksCall {
    return try Iotexapi_APIServiceGetRawBlocksCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getLogs(_ request: Iotexapi_GetLogsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetLogsResponse {
    return try Iotexapi_APIServiceGetLogsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getLogs(_ request: Iotexapi_GetLogsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetLogsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetLogsCall {
    return try Iotexapi_APIServiceGetLogsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByActionHashResponse {
    return try Iotexapi_APIServiceGetTransactionLogByActionHashCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByActionHashCall {
    return try Iotexapi_APIServiceGetTransactionLogByActionHashCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse {
    return try Iotexapi_APIServiceGetTransactionLogByBlockHeightCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetTransactionLogByBlockHeightCall {
    return try Iotexapi_APIServiceGetTransactionLogByBlockHeightCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  public func streamBlocks(_ request: Iotexapi_StreamBlocksRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamBlocksCall {
    return try Iotexapi_APIServiceStreamBlocksCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  public func streamLogs(_ request: Iotexapi_StreamLogsRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Iotexapi_APIServiceStreamLogsCall {
    return try Iotexapi_APIServiceStreamLogsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetActPoolActionsResponse {
    return try Iotexapi_APIServiceGetActPoolActionsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getActPoolActions(_ request: Iotexapi_GetActPoolActionsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetActPoolActionsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetActPoolActionsCall {
    return try Iotexapi_APIServiceGetActPoolActionsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEvmTransfersByActionHashResponse {
    return try Iotexapi_APIServiceGetEvmTransfersByActionHashCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getEvmTransfersByActionHash(_ request: Iotexapi_GetEvmTransfersByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEvmTransfersByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByActionHashCall {
    return try Iotexapi_APIServiceGetEvmTransfersByActionHashCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetEvmTransfersByBlockHeightResponse {
    return try Iotexapi_APIServiceGetEvmTransfersByBlockHeightCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getEvmTransfersByBlockHeight(_ request: Iotexapi_GetEvmTransfersByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetEvmTransfersByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetEvmTransfersByBlockHeightCall {
    return try Iotexapi_APIServiceGetEvmTransfersByBlockHeightCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetElectionBucketsResponse {
    return try Iotexapi_APIServiceGetElectionBucketsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getElectionBuckets(_ request: Iotexapi_GetElectionBucketsRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetElectionBucketsResponse?, CallResult) -> Void) throws -> Iotexapi_APIServiceGetElectionBucketsCall {
    return try Iotexapi_APIServiceGetElectionBucketsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}
public protocol Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCall: ClientCallUnary {}

fileprivate final class Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCallBase: ClientCallUnaryBase<Iotexapi_GetTransactionLogByActionHashRequest, Iotexapi_GetTransactionLogByActionHashResponse>, Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCall {
  override class var method: String { return "/iotexapi.TransactionLogService/GetTransactionLogByActionHash" }
}

public protocol Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCall: ClientCallUnary {}

fileprivate final class Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCallBase: ClientCallUnaryBase<Iotexapi_GetTransactionLogByBlockHeightRequest, Iotexapi_GetTransactionLogByBlockHeightResponse>, Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCall {
  override class var method: String { return "/iotexapi.TransactionLogService/GetTransactionLogByBlockHeight" }
}


/// Instantiate Iotexapi_TransactionLogServiceServiceClient, then call methods of this protocol to make API calls.
public protocol Iotexapi_TransactionLogServiceService: ServiceClient {
  /// Synchronous. Unary.
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByActionHashResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCall

  /// Synchronous. Unary.
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCall

}

public extension Iotexapi_TransactionLogServiceService {
  /// Synchronous. Unary.
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest) throws -> Iotexapi_GetTransactionLogByActionHashResponse {
    return try self.getTransactionLogByActionHash(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCall {
    return try self.getTransactionLogByActionHash(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse {
    return try self.getTransactionLogByBlockHeight(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCall {
    return try self.getTransactionLogByBlockHeight(request, metadata: self.metadata, completion: completion)
  }

}

public final class Iotexapi_TransactionLogServiceServiceClient: ServiceClientBase, Iotexapi_TransactionLogServiceService {
  /// Synchronous. Unary.
  public func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByActionHashResponse {
    return try Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getTransactionLogByActionHash(_ request: Iotexapi_GetTransactionLogByActionHashRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByActionHashResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCall {
    return try Iotexapi_TransactionLogServiceGetTransactionLogByActionHashCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata) throws -> Iotexapi_GetTransactionLogByBlockHeightResponse {
    return try Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  public func getTransactionLogByBlockHeight(_ request: Iotexapi_GetTransactionLogByBlockHeightRequest, metadata customMetadata: Metadata, completion: @escaping (Iotexapi_GetTransactionLogByBlockHeightResponse?, CallResult) -> Void) throws -> Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCall {
    return try Iotexapi_TransactionLogServiceGetTransactionLogByBlockHeightCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

